packages:
  - '.'

allowBuilds:
  protobufjs: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@drunk-pulumi/azure-providers'
  - prettier@3.9.1

patchedDependencies:
  buffer-equal-constant-time@1.0.1: patches/buffer-equal-constant-time@1.0.1.patch
